config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  resources :books, only: [:show, :index]
  resources :authors, only: [:show]
  resources :categories, only: [:show]
  resources :reviews, only: [:create]
  resources :sales, only: [:index, :create, :destroy]
  resources :media, only: [:show]
  post '/bills/new', to: 'bills#new', as: :bill
  post '/contacts', to: 'contacts#new', as: :contact

  namespace :manager do
    resources :books, except: [:show]
    resources :users
    resources :authors, only: [:index, :destroy]
    resources :categories, only: [:index, :destroy]
    resources :reviews, only: [:index]
    resources :sales, only: [:index]
    resources :media, except: [:destroy]
    root 'media#index'
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount StripeEvent::Engine, at: '/stripe_webhooks'
end

app/models/book.rb
class Book < ApplicationRecord
  paginates_per 20

  belongs_to :publisher, optional: true
  has_one_attached :pdf_file
  has_many :reviews, dependent: :destroy
  has_many :sales
  has_many :users, through: :sales
  has_and_belongs_to_many :authors, -> { distinct }
  has_and_belongs_to_many :categories, -> { distinct }
  
  after_create :create_product
  after_update :update_product
  before_destroy :cascade

  validates :title, presence: true
  validates :price, presence: true
  validates :description, presence: true
  validates :image_link, presence: true ,:format => URI::regexp(%w(http https))
  validates :isbn, uniqueness:  true
  validate :check_isbn_length
  validate :correct_document_mime_type
  validate :valid_date?
  validates_numericality_of :price, greater_than_or_equal_to: 0
  validates_numericality_of :page_count, greater_than: 0

  def self.newest num
    where.not(product_id: nil).last(num).reverse
  end

  def self.best_seller num
    left_joins(:sales).group(:id).where("sales.status" => :completed)
    .order('COUNT(sales.id) DESC').limit(num)
  end

  def correct_document_mime_type
    if pdf_file.attached? && !pdf_file.content_type.in?(%w(application/pdf))
      pdf_file.purge
      errors.add(:pdf_file, 'Must be a PDF or a DOC file')
    end
  end

  def publisher_name
    publisher.name if publisher
  end

  def create_publisher publisher_params
    publisher = Publisher.find_or_initialize_by(publisher_params)
    if publisher.save
      self.publisher = publisher
    end
  end

  def create_authors authors_params
    cascade_authors
    self.authors.clear
    authors_params[:names].split(',').each do |value|
      author = Author.find_or_initialize_by({name: human_name(value)})
      if author.save
        self.authors.append(author)
      end
    end
  end

  def create_categories categories_params
    cascade_categories
    self.categories.clear
    categories_params[:names].split(',').each do |value|
      category = Category.find_or_initialize_by({name: human_name(value)})
      if category.save
        self.categories.append(category)
      end
    end
  end

  private
    def valid_date?
      if published_date.present? and published_date > Time.now 
        errors.add(:published_date, "can't be in the future!")
      end
    end

    def check_isbn_length
      unless isbn.size == 10 or isbn.size == 13
        errors.add(:isbn, "length must be 10 or 13")
      end
    end

    def cascade
      cascade_authors
      cascade_categories
    end

    def cascade_authors
      authors.each do |author|
        if author.books.size == 1
          author.destroy
        end
      end
    end

    def cascade_categories
      categories.each do |category|
        if category.books.size == 1
          category.destroy
        end
      end
    end

    def create_product
      CreateProductJob.perform_later self
    end

    def update_product
      UpdateProductJob.perform_later self
    end

    def human_name name
      name.split.map(&:capitalize).join(' ')
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  layout 'application'
  load_and_authorize_resource

  def index
    @q = Book.where.not(product_id: nil).ransack(params[:q])
    @books = @q.result.order(:title).page(params[:page])
  end

end

app/controllers/manager/authors_controller.rb
module Manager
  class AuthorsController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    def index
      @authors = Author.all
    end

    def destroy
      @author.destroy 
      redirect_to manager_authors_url, notice:  t("messages.success.destroy", model: @author.class.name)
    end
  end
end

app/controllers/manager/books_controller.rb
module Manager
  class BooksController < ActionController::Base
    layout 'admin'
    load_and_authorize_resource

    add_breadcrumb I18n.t('default.dashboard'), :manager_root_path
    add_breadcrumb I18n.t('activerecord.models.book.other'), :manager_books_path

    def index
      @books = Book.all
    end
  
    def create
      @book = Book.new(book_params)
      @book.create_publisher(publisher_params)
      @book.create_authors(author_params)
      @book.create_categories(category_params)
      if @book.save
        redirect_to manager_books_path, notice: t("messages.success.create", model: @book.class.name)
      else
        render :new
      end
      
    end
  
    def update      
      @book.create_publisher(publisher_params)
      @book.create_authors(author_params)
      @book.create_categories(category_params)
      if @book.update(book_params)
        redirect_to manager_books_path, notice: t("messages.success.update", model: @book.class.name)
      else
        render :edit
      end

    end
  
    def destroy
      begin
        @book.destroy
        redirect_to manager_books_url, notice: t("messages.success.destroy", model: @book.class.name)
      rescue ActiveRecord::InvalidForeignKey
        redirect_to manager_books_url, alert: t("messages.fail.destroy", model: @book.class.name)
      end
    end
  
    private
      def book_params
        params.require(:book).permit(:title, :publisher_id, :published_date,
           :description, :isbn, :page_count, :image_link, :language, :price, 
           :pdf_file)
      end
  
      def publisher_params
        params.require(:publisher).permit(:name)
      end
  
      def author_params
        params.require(:authors).permit(:names)
      end
  
      def category_params
        params.require(:categories).permit(:names)
      end
  end
end

app/controllers/manager/categories_controller.rb
module Manager
  class CategoriesController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    def index
      @categories = Category.all
    end

    def destroy
      @category.destroy 
      redirect_to manager_categories_url, notice:  t("messages.success.destroy", model: @category.class.name)
    end
  end
end

app/controllers/manager/dashboard_controller.rb
module Manager
  class DashboardController < ApplicationController
    layout 'admin'

    add_breadcrumb I18n.t('default.dashboard'), :manager_root_path

    def index
      authorize! :create, Book
    end
  end
end

app/controllers/manager/media_controller.rb
module Manager
  class MediaController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    def index
      @medium = Medium.first_or_initialize
      if @medium.persisted?
        render :show
      else
        render :new
      end
    end

    def create
      if @medium.save
        redirect_to manager_media_path, notice: t("messages.success.create", model: @medium.class.name)
      else
        render :new
      end
    end

    def update
      if @medium.update(medium_params)
        redirect_to manager_media_path, notice: t("messages.success.update", model: @medium.class.name)
      else
        render :edit
      end
    end

    private
      def medium_params
        params.require(:medium).permit(:address, :call, :email,
           :timing, :facebook, :instagram, :twitter, :pinterest)
      end
  end
end

app/controllers/manager/reviews_controller.rb
module Manager
  class ReviewsController < ApplicationController
    load_and_authorize_resource
    layout 'admin'

    def index
      @reviews = Review.all
    end
  end
end

app/controllers/manager/sales_controller.rb
module Manager
  class SalesController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    def index
      @sales = Sale.all.order(:payment_time).reverse
    end
  end
end

app/controllers/manager/users_controller.rb
module Manager
  class UsersController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    add_breadcrumb I18n.t('default.dashboard'), :manager_root_path
    add_breadcrumb I18n.t('activerecord.models.user.other'), :manager_users_path

    def create
      if @user.save
        redirect_to manager_users_path, notice: t("messages.success.create", model: @user.class.name)
      else
        render 'new'
      end
    end

    def update
      if @user.update(update_user_params)
        redirect_to manager_users_path, notice: t("messages.success.update", model: @user.class.name)
      else
        render 'edit'
      end
    end

    def destroy
      @user.destroy!
      redirect_to manager_users_url, notice: t("messages.success.destroy", model: @user.class.name)
    end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :type)
    end

    def update_user_params
      params[:user][:password].present? ?
        params.require(:user).permit(:email, :type, :password, :password_confirmation) :
        params.require(:user).permit(:email, :type)
    end
  end
end

app/helpers/book_helper.rb
module BookHelper
    def csv_names(list)
        list.pluck(:name).join(', ')
    end

    def human_price(price)
        price == 0 ? "Free": "$" + price.to_s
    end

    def buy_book_button_name
        @book.price == 0 ? t('default.own_it') : t('default.add_to_cart')
    end
end

app/views/manager/books/_form.html.erb
<%= form_with(model: [:manager, book], local: true, class: "form-horizontal",
              html: {autocomplete: "off"}) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, t('default.error')) %></h2>

      <ul>
        <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= form.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= label_tag "publisher_name", t('activerecord.models.publisher.one'), class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <% if book.publisher.present? %>
        <%= text_field_tag "publisher[name]", book.publisher.name, class: "form-control" %>
      <% else %>
        <%= text_field_tag "publisher[name]", nil, class: "form-control" %>
      <% end %>
    </div>
  </div>

  <%= render 'taginput', list: book.authors,
             singular: "author", plural: "authors" %>

  <%= render 'taginput', list: book.categories,
             singular: "category", plural: "categories" %>

  <div class="form-group">
    <%= form.label :published_date, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= form.date_field :published_date, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :description, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= form.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :isbn, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= form.text_field :isbn, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :page_count, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= form.number_field :page_count, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :image_link, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= form.text_field :image_link, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :language, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= form.text_field :language, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :pdf_file, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <% if @book.pdf_file.attached? %>
        <%= @book.pdf_file.blob.filename %>
        <%= link_to @book.pdf_file.purge do %>
          <i class="fa fa-times" aria-hidden="true"></i>
        <% end %>
      <% end %>
      <%= form.file_field :pdf_file, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label :price, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= form.text_field :price, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <%= form.submit class: "mb-xs mt-xs mr-xs btn btn-primary btn-lg btn-block" %>
    </div>
  </div>
<% end %>

app/views/manager/books/_search_book.html.erb
<form autocomplete="off" class="form-horizontal">
  <div class="form-group">
    <%= label_tag nil, t('default.search'), class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <div class="input-group input-search">
        <div class="autocomplete" id=search_google_book>
          <%= text_field_tag "search_google_book", nil, class: "form-control", id: "search_google_book_input", placeholder: t('default.search') %>
          <span class="input-group-btn">
                  <%= button_tag t('book.view.add_book'),
                                 :type => 'button', id: "search_google_book_submit", class: "btn btn-default" do %>
                  <i class="fa fa-search"></i>
                  <% end %>
                </span>
        </div>
      </div>
    </div>
  </div>
  <div class="form-group"></div>
</form>

app/views/manager/books/_taginput.html.erb
<div class="form-group">
  <%= label_tag plural, t("activerecord.models.#{singular}.other"), class: "col-md-3 control-label" %>
  <div class="col-md-6">
    <%= text_field_tag "#{plural}[names]", csv_names(list),
     {id: "#{plural}-input", 'data-role' => "tagsinput",
      'data-tag-class' => "label label-primary", class: "form-control"} %>
  </div>
</div>

app/views/manager/books/edit.html.erb
<% title t('breadcrumbs.edit', model: Book.name) %>
<%= render 'form', book: @book %>

app/views/manager/books/index.html.erb
<% title t('activerecord.models.book.other') %>
<table class="table table-bordered table-striped mb-none table-with-details">
  <thead>
  <tr>
    <th><%= Book.human_attribute_name(:title) %></th>
    <th><%= Book.human_attribute_name(:isbn) %></th>
    <th><%= Book.human_attribute_name(:published_date) %></th>
    <th><%= Book.human_attribute_name(:page_count) %></th>
    <th><%= Book.human_attribute_name(:language) %></th>
    <th><%= Book.human_attribute_name(:product_id) %></th>
    <th><%= Book.human_attribute_name(:price) %></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @books.each do |book| %>
    <tr class="gradeX">
      <td><%= book.title %></td>
      <td><%= book.isbn %></td>
      <td><%= book.published_date %></td>
      <td><%= book.page_count %></td>
      <td><%= book.language %></td>
      <td><%= book.product_id %></td>
      <td><%= book.price %></td>
      <td>
        <%= render partial: 'shared/admin/table_actions',
                    locals: {edit_path: :edit_manager_book_path,
                              delete_path: :manager_book_path,
                              item_id: book.id} %>
      </td>
      <template id="table_hidden_data">
        <table class="table mb-none">
            <div class="row no-gutters">
              <div class="col-md-2">
                <%= image_tag book.image_link, class: "card-img" %>
              </div>
              <div class="col-md-10">
                <div class="card-body">
                  <h5 class="card-title"><%= book.title %></h5>
                  <p class="card-text"><small class="text-muted"><%= csv_names(book.authors) %></small></p>
                  <p class="card-text"><%= book.description %></p>
                  <p class="card-text"><small class="text-muted"><%= csv_names(book.categories) %></small></p>
                  <p class="card-text"><small class="text-muted"><%= book.publisher_name %></small></p>
                </div>
              </div>
            </div>
        </div>
      </template>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to t('book.view.new_book'), new_manager_book_path, class: "btn btn-primary" %>

app/views/manager/books/new.html.erb
<% title t('breadcrumbs.new', model: Book.name) %>
<%= render 'search_book' %>
<%= render 'form', book: @book %>