config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  resources :books, only: [:show, :index]
  resources :authors, only: [:show]
  resources :categories, only: [:show]
  resources :reviews, only: [:create]
  resources :sales, only: [:index, :create, :destroy]
  resources :media, only: [:show]
  post '/bills/new', to: 'bills#new', as: :bill
  post '/contacts', to: 'contacts#new', as: :contact

  namespace :manager do
    resources :books, except: [:show]
    resources :users
    resources :authors, only: [:index, :destroy]
    resources :categories, only: [:index, :destroy]
    resources :reviews, only: [:index]
    resources :sales, only: [:index]
    resources :media, except: [:destroy]
    root 'media#index'
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount StripeEvent::Engine, at: '/stripe_webhooks'
end

app/views/shared/_about.html.erb
<section class="about-sec">
  <div class="about-img">
    <figure class='about-fig'></figure>
  </div>
  <div class="about-content">
    <h2><%= I18n.t("home.about.title")%></h2>
    <p><%= I18n.t("home.about.description") %></p>
    <div class="btn-sec">
      <%= link_to t('default.shop_books'), books_path, class: "btn yellow" %>
      <%= link_to t('default.subscriptions'), new_user_registration_path, class: "btn black" %>
    </div>
  </div>
</section>

app/views/shared/_book_collection.html.erb
<section class="recent-book-sec">
  <div class="container">
    <div class="title">
      <h2><%= title %></h2>
      <hr>
    </div>
    <div class="row">
      <% books.each do |book| %>
        <div class="col-lg-2 col-md-3 col-sm-4">
          <div class="item">
            <%= image_tag book.image_link, alt:"img"%>
            <h3><%= link_to book.title, book %></h3>
            <h6><span class="price"><%= human_price(book.price) %></span></h6>
          </div>
        </div>
      <% end %>
    </div>
    <div class="btn-sec">
      <%= link_to t('home.view_books'), books_path, class: "btn gray-btn" %>
    </div>
  </div>
</section>

app/views/shared/_books.html.erb
<section class="recomended-sec">
  <div class="container">
    <div class="title">
      <h2><%= title %></h2>
      <hr>
    </div>
    <div class="row">
      <% books.each do |book| %>
        <div class="col-lg-3 col-md-6 mb-4">
          <div class="item">
            <%= image_tag book.image_link, alt: "img" %>
            <h3><%= book.title %></h3>
            <h6>
              <span class="price"><%= human_price(book.price) %></span> /
              <%= link_to t('default.buy_now'), '#'%></h6>
            <div class="hover">
              <%= link_to book do%>
              <span><i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
              <%end%>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <%= paginate @books %>
  </div>
</section>

app/views/shared/_contact_us_form.html.erb
<div class="form">
  <h3>Quick Contact us</h3>
  <h6>We are now offering some good discount
    on selected books go and shop them</h6>
    <%= form_for :contact, url: contact_url do |f| %>
      <div class="row">
        <div class="col-md-6">
          <%= f.text_field :name, placeholder: t('contacts.placeholder.name')%>
        </div>
        <div class="col-md-6">
          <%= f.text_field :email, placeholder: t('contacts.placeholder.email')%>
        </div>
        <div class="col-md-12">
          <%= f.text_area :message, placeholder: t('contacts.placeholder.message')%>
        </div>
      </div>
      <div class="col-md-12">
        <%= f.button t("contacts.actions.save"), class: "btn black" %>
      </div>
    <% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |type, msg| %>
  <%= content_tag :div, class: flash_class(type) do %>
    <%= msg %>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <% if @medium.present? %>
          <div class="address">
            <h4><%= t('home.our_address') %></h4>
            <h6><%= @medium.address%></h6>
            <h6><%= t('home.call') %> : <%= @medium.call %></h6>
            <h6><%= t('home.email') %> : <%= @medium.email %></h6>
          </div>
          <div class="timing">
            <h4><%= t('home.timing') %></h4>
            <% @medium.timing.split("\n").each do |line| %>
              <h6><%= line %></h6>
            <% end %>
          </div>
        <% end %>
      </div>
      <div class="col-md-5">
        <%= render partial: 'shared/contact_us_form'  %>
      </div>
    </div>
  </div>
  <div class="copy-right">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <h5>(C) 2017. All Rights Reserved. BookStore Wordpress Theme</h5>
        </div>
        <div class="col-md-6">
          <% if @medium.present? %>
            <div class="share align-middle">
              <span class="fb">
                <%= link_to @medium.facebook , class: "btn link" do %>
                  <i class="fa fa-facebook-official" aria-hidden="true"></i>
                <% end %>
              </span>
              <span class="instagram">
                <%= link_to @medium.instagram , class: "btn link" do %>
                  <i class="fa fa-instagram"></i>
                <% end %>
              </span>
              <span class="twitter">
                <%= link_to @medium.twitter , class: "btn link" do %>
                  <i class="fa fa-twitter"></i>
                <% end %>
              </span>
              <span class="pinterest">
                <%= link_to @medium.pinterest , class: "btn link" do %>
                  <i class="fa fa-pinterest"></i>
                <% end %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <div class="main-menu">
    <div class="container">
      <%= render partial: "shared/navbar" %>
    </div>
  </div>
</header>

app/views/shared/_megamenu.html.erb
<div class="dropdown-menu megamenu" role="menu">
    <div class="row">
        <% list.in_groups(4, false) do |column| %>
        <div class="col-md-3">
            <% column.each do |item| %>
            <%= link_to item.name, item, class: "nav-link"%>
            <%end%>
        </div>
        <% end %>
    </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to root_url, class: "navbar-brand" do %>
    <%= image_tag "logo.png", alt: "logo" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="navbar-item">
        <%= link_to t('default.home'), root_path, class: "nav-link" %>
      </li>
      <% if current_user_admin? %>
        <li class="navbar-item">
          <%= link_to t('default.dashboard'), manager_root_url, class: "nav-link" %>
        </li>
      <% end %>
      <li class="navbar-item">
        <%= link_to t('default.shop'), books_path, class: "nav-link" %>
      </li>
      <li id="authors_list" class="navbar-item dropdown has-megamenu">
        <%= link_to t('activerecord.models.author.other'), '#',
         class: "nav-link dropdown-toggle", :"data-toggle" => "dropdown"%>
         <%= render 'shared/megamenu', list: @authors %>
      </li>
      <li id="categories_list" class="navbar-item dropdown has-megamenu">
        <%= link_to t('activerecord.models.category.other'), '#',
         class: "nav-link dropdown-toggle", :"data-toggle" => "dropdown"%>
         <%= render 'shared/megamenu', list: @categories %>
      </li>
      <li class="navbar-item">
        <% if user_signed_in? %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
    <% if current_user_customer? %>
      <div class="cart my-2 my-lg-0">
        <%= link_to sales_path(cart: true), class: "btn link black" do %>
          <span>
            <i class="fa fa-shopping-cart" aria-hidden="true"></i></span>
            <% if cart_size > 0 %>
              <span class="quantity"><%= cart_size %></span>
            <% end %>
        <%end%>
      </div>
      <div class="cart my-2 my-lg-0">
        <%= link_to sales_path, class: "btn link black" do %>
          <span><i class="fa fa-history" aria-hidden="true"></i></span>
        <%end%>
      </div>
    <% end %>
    <%= render partial: 'shared/search_form' %>
  </div>
</nav>

app/views/shared/_recommended.html.erb
<section class="recomended-sec">
  <div class="container">
    <div class="title">
      <h2>highly recommendes books</h2>
      <hr>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="item">
          <%= image_tag "img1.jpg", alt: "img" %>
          <h3>how to be a bwase</h3>
          <h6><span class="price">$49</span> / <a href="#">Buy Now</a></h6>
          <div class="hover">
            <a href="product-single.html">
              <span><i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="item">
          <%= image_tag "img2.jpg", alt:"img"%>
          <h3>How to write a book...</h3>
          <h6><span class="price">$19</span> / <a href="#">Buy Now</a></h6>
          <span class="sale">Sale !</span>
          <div class="hover">
            <a href="product-single.html">
              <span><i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="item">
          <%= image_tag "img3.jpg", alt: "img" %>
          <h3>7-day self publish...</h3>
          <h6><span class="price">$49</span> / <a href="#">Buy Now</a></h6>
          <div class="hover">
            <a href="product-single.html">
              <span><i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
            </a>
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="item">
          <%= image_tag "img4.jpg", alt: "img" %>
          <h3>wendy doniger</h3>
          <h6><span class="price">$49</span> / <a href="#">Buy Now</a></h6>
          <div class="hover">
            <a href="product-single.html">
              <span><i class="fa fa-long-arrow-right" aria-hidden="true"></i></span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/shared/_search_form.html.erb
<%= search_form_for @q, class: "form-inline my-2 my-lg-0" do |f| %>
  <%= f.search_field :title_cont, placeholder: t("login.placeholder.search_book"), class: "form-control mr-sm-2" %>
  <span class="fa fa-search"></span>
<% end %>