config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  resources :books, only: [:show, :index]
  resources :authors, only: [:show]
  resources :categories, only: [:show]
  resources :reviews, only: [:create]
  resources :sales, only: [:index, :create, :destroy]
  resources :media, only: [:show]
  post '/bills/new', to: 'bills#new', as: :bill
  post '/contacts', to: 'contacts#new', as: :contact

  namespace :manager do
    resources :books, except: [:show]
    resources :users
    resources :authors, only: [:index, :destroy]
    resources :categories, only: [:index, :destroy]
    resources :reviews, only: [:index]
    resources :sales, only: [:index]
    resources :media, except: [:destroy]
    root 'media#index'
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount StripeEvent::Engine, at: '/stripe_webhooks'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  attribute :type, default: 'Customer'
  
  has_many :sales, dependent: :nullify
  has_many :books, through: :sales 
  has_many :reviews, dependent: :destroy

  before_validation :create_customer, on: :create
  after_create :send_welcome_email

  validate :has_customer_id

  def admin?
    type == "Admin"
  end

  def customer?
    type == "Customer"
  end


  private
    def has_customer_id
      if customer? && customer_id.nil?
        errors.add(:customer_id, I18n.t('messages.fail.connection_failed'))
      end
    end

    def create_customer
      begin
        customer = Stripe::Customer.create()
        self.customer_id = customer.id
      rescue => e
        Rails.logger.debug e.message
      end
    end

    def send_welcome_email
      UserMailer.with(user: self).welcome_email.deliver_later
    end
end

app/controllers/manager/authors_controller.rb
module Manager
  class AuthorsController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    def index
      @authors = Author.all
    end

    def destroy
      @author.destroy 
      redirect_to manager_authors_url, notice:  t("messages.success.destroy", model: @author.class.name)
    end
  end
end

app/controllers/manager/books_controller.rb
module Manager
  class BooksController < ActionController::Base
    layout 'admin'
    load_and_authorize_resource

    add_breadcrumb I18n.t('default.dashboard'), :manager_root_path
    add_breadcrumb I18n.t('activerecord.models.book.other'), :manager_books_path

    def index
      @books = Book.all
    end
  
    def create
      @book = Book.new(book_params)
      @book.create_publisher(publisher_params)
      @book.create_authors(author_params)
      @book.create_categories(category_params)
      if @book.save
        redirect_to manager_books_path, notice: t("messages.success.create", model: @book.class.name)
      else
        render :new
      end
      
    end
  
    def update      
      @book.create_publisher(publisher_params)
      @book.create_authors(author_params)
      @book.create_categories(category_params)
      if @book.update(book_params)
        redirect_to manager_books_path, notice: t("messages.success.update", model: @book.class.name)
      else
        render :edit
      end

    end
  
    def destroy
      begin
        @book.destroy
        redirect_to manager_books_url, notice: t("messages.success.destroy", model: @book.class.name)
      rescue ActiveRecord::InvalidForeignKey
        redirect_to manager_books_url, alert: t("messages.fail.destroy", model: @book.class.name)
      end
    end
  
    private
      def book_params
        params.require(:book).permit(:title, :publisher_id, :published_date,
           :description, :isbn, :page_count, :image_link, :language, :price, 
           :pdf_file)
      end
  
      def publisher_params
        params.require(:publisher).permit(:name)
      end
  
      def author_params
        params.require(:authors).permit(:names)
      end
  
      def category_params
        params.require(:categories).permit(:names)
      end
  end
end

app/controllers/manager/categories_controller.rb
module Manager
  class CategoriesController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    def index
      @categories = Category.all
    end

    def destroy
      @category.destroy 
      redirect_to manager_categories_url, notice:  t("messages.success.destroy", model: @category.class.name)
    end
  end
end

app/controllers/manager/dashboard_controller.rb
module Manager
  class DashboardController < ApplicationController
    layout 'admin'

    add_breadcrumb I18n.t('default.dashboard'), :manager_root_path

    def index
      authorize! :create, Book
    end
  end
end

app/controllers/manager/media_controller.rb
module Manager
  class MediaController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    def index
      @medium = Medium.first_or_initialize
      if @medium.persisted?
        render :show
      else
        render :new
      end
    end

    def create
      if @medium.save
        redirect_to manager_media_path, notice: t("messages.success.create", model: @medium.class.name)
      else
        render :new
      end
    end

    def update
      if @medium.update(medium_params)
        redirect_to manager_media_path, notice: t("messages.success.update", model: @medium.class.name)
      else
        render :edit
      end
    end

    private
      def medium_params
        params.require(:medium).permit(:address, :call, :email,
           :timing, :facebook, :instagram, :twitter, :pinterest)
      end
  end
end

app/controllers/manager/reviews_controller.rb
module Manager
  class ReviewsController < ApplicationController
    load_and_authorize_resource
    layout 'admin'

    def index
      @reviews = Review.all
    end
  end
end

app/controllers/manager/sales_controller.rb
module Manager
  class SalesController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    def index
      @sales = Sale.all.order(:payment_time).reverse
    end
  end
end

app/controllers/manager/users_controller.rb
module Manager
  class UsersController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    add_breadcrumb I18n.t('default.dashboard'), :manager_root_path
    add_breadcrumb I18n.t('activerecord.models.user.other'), :manager_users_path

    def create
      if @user.save
        redirect_to manager_users_path, notice: t("messages.success.create", model: @user.class.name)
      else
        render 'new'
      end
    end

    def update
      if @user.update(update_user_params)
        redirect_to manager_users_path, notice: t("messages.success.update", model: @user.class.name)
      else
        render 'edit'
      end
    end

    def destroy
      @user.destroy!
      redirect_to manager_users_url, notice: t("messages.success.destroy", model: @user.class.name)
    end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :type)
    end

    def update_user_params
      params[:user][:password].present? ?
        params.require(:user).permit(:email, :type, :password, :password_confirmation) :
        params.require(:user).permit(:email, :type)
    end
  end
end

app/views/manager/users/_form.html.erb

<%= form_with model: @user.becomes(User), url: url, local: true do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, t(:error, scope: [:default])) %></h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :email, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= f.email_field :email, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= f.password_field :password_confirmation, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :type, class: "col-md-3 control-label" %>
    <div class="col-md-6">
      <%= f.select :type, options_for_select(['Admin', 'Customer'], @user.type), class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-3"></div>
    <div class="col-md-6">
      <%= f.submit class: "mb-xs mt-xs mr-xs btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/manager/users/edit.html.erb
<% title t('breadcrumbs.edit', model: User.name) %>

<%= render partial: 'form', locals: {url: manager_user_url(@user)} %>

app/views/manager/users/index.html.erb
<% title t('activerecord.models.user.other') %>

<table class="table table-bordered table-striped mb-none" id="datatable-user">
  <thead>
  <tr>
    <th><%= User.human_attribute_name(:email) %></th>
    <th><%= User.human_attribute_name(:type) %></th>
    <th><%= User.human_attribute_name(:customer_id) %></th>
    <th><%= User.human_attribute_name(:created_at) %></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr class="gradeX">
      <td><%= user.email %></td>
      <td><%= user.type %></td>
      <td><%= user.customer_id %></td>
      <td><%= user.created_at %></td>
      <td><%= render partial: 'shared/admin/table_actions',
                      locals: {edit_path: :edit_manager_user_path,
                                delete_path: :manager_user_path,
                                item_id: user.id} %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to  t('breadcrumbs.new', model: User.name), new_manager_user_url, class: "btn btn-primary" %>

app/views/manager/users/new.html.erb
<% title t('breadcrumbs.new', model: User.name) %>

<%= render partial: 'form', locals: {url: manager_users_url} %>