config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'home#index'

  devise_for :users, controllers: {sessions: 'sessions', registrations: 'registrations'}

  resources :books, only: [:show, :index]
  resources :authors, only: [:show]
  resources :categories, only: [:show]
  resources :reviews, only: [:create]
  resources :sales, only: [:index, :create, :destroy]
  resources :media, only: [:show]
  post '/bills/new', to: 'bills#new', as: :bill
  post '/contacts', to: 'contacts#new', as: :contact

  namespace :manager do
    resources :books, except: [:show]
    resources :users
    resources :authors, only: [:index, :destroy]
    resources :categories, only: [:index, :destroy]
    resources :reviews, only: [:index]
    resources :sales, only: [:index]
    resources :media, except: [:destroy]
    root 'media#index'
  end

  authenticate :user, ->(user) { user.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  mount StripeEvent::Engine, at: '/stripe_webhooks'
end

app/models/sale.rb
class Sale <  ActiveRecord::Base
  paginates_per 10
  belongs_to :user, required: true
  belongs_to :book, required: true
  
  attribute :status, default: :in_progress, presence: true
  enum status: [ :in_progress, :completed ]

  validates_uniqueness_of :user_id, :scope => [:book_id]
end

app/controllers/manager/sales_controller.rb
module Manager
  class SalesController < ApplicationController
    layout 'admin'
    load_and_authorize_resource

    def index
      @sales = Sale.all.order(:payment_time).reverse
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
    layout 'application'
    load_and_authorize_resource

    def index
      if params[:cart]
        @sales = @sales.in_progress.page(params[:page])
        render 'cart'
      else
        @sales = @sales.completed.page(params[:page])
        render 'history'
      end
    end
    
    def create
      @sale = current_user.sales.new(sale_params)
      if @sale.save
          if @sale.book.price == 0
            @sale.update({status: :completed, payment_time: Time.now})
            flash[:notice] = t('default.messages.added_to_profile')
          else
            flash[:notice] = t("default.messages.added_to_cart")
          end
          redirect_to book_path(book_id)
      else
          redirect_to book_path(book_id), alert: t("default.error_messages.cannot_add_to_cart")
      end
    end

    def destroy
      @sale.destroy
      redirect_to sales_url(cart: true), notice: t("default.messages.removed_from_cart")
    end

    private
      def sale_params
        params.permit(:book_id)
      end

      def book_id
        sale_params[:book_id]
      end
end

app/helpers/sale_helper.rb
module SaleHelper
    def total_price
        @sales.sum do |sale|
            sale.book.price
        end
    end

    def extract_products_params
        (@sales.map {|sale| sale.book}).as_json(only: [:product_id, :price])
    end
end

app/views/sales/cart.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <table class="table table-sm table-hover table-bordered text-center">
                <thead>
                    <tr>
                        <th><%= Book.human_attribute_name(:title) %></th>
                        <th><%= Book.human_attribute_name(:isbn).upcase %></th>
                        <th><%= Book.human_attribute_name(:price) %></th>
                        <th><%= t('default.remove') %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @sales.each do |sale| %>
                    <tr>
                        <td><%= sale.book.title %></td>
                        <td><%= sale.book.isbn %></td>
                        <td><%= sale.book.price %></td>
                        <td>
                            <div class="center">
                                <%= link_to sale_path(sale), method: :delete do %>
                                <i class="fa fa-times remove square" aria-hidden="true"></i>
                                <% end %>
                            </div>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <%= paginate @sales %>
        </div>
        <div class="col-md-2">
            <%= render 'bills/form', products: extract_products_params, total_price: total_price %>
        </div>
    </div>
</div>

app/views/sales/history.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10">
      <table class="table table-sm table-hover table-bordered text-center">
        <thead>
          <tr>
            <th><%= Book.human_attribute_name(:title) %></th>
            <th><%= Book.human_attribute_name(:isbn).upcase %></th>
            <th><%= Book.human_attribute_name(:price) %></th>
            <th><%= Book.human_attribute_name(:payment_time) %></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @sales.each do |sale| %>
          <tr>
            <td><%= sale.book.title %></td>
            <td><%= sale.book.isbn %></td>
            <td><%= sale.book.price %></td>
            <td><%= sale.payment_time %></td>
            <td>
              <%= link_to book_url(sale.book.id) do %>
                <i class="fa fa-eye" aria-hidden="true"></i>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @sales %>
    </div>
  </div>
</div>

app/views/sales/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-10">
            <table class="table table-sm table-hover table-bordered text-center">
                <thead>
                    <tr>
                        <th><%= Book.human_attribute_name(:title) %></th>
                        <th><%= Book.human_attribute_name(:isbn).upcase %></th>
                        <th><%= Book.human_attribute_name(:price) %></th>
                        <th><%= t('default.remove') %></th>
                    </tr>
                </thead>
                <tbody>
                    <% @sales.each do |sale| %>
                    <tr>
                        <td><%= sale.book.title %></td>
                        <td><%= sale.book.isbn %></td>
                        <td><%= sale.book.price %></td>
                        <td>
                            <div class="center">
                                <%= link_to sale_path(sale), method: :delete do %>
                                <i class="fa fa-times remove square" aria-hidden="true"></i>
                                <% end %>
                            </div>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
            <%= paginate @sales %>
        </div>
        <div class="col-md-2">
            <%= render 'bills/form', products: extract_products_params, total_price: total_price %>
        </div>
    </div>
</div>